spring:
  cloud:
    gcp:
      project-id: taxitycoon
    stream:
      default-binder: solace
      function:
        definition: bridgeGcpToSolace
      bindings:
        bridgeGcpToSolace-in-0:
          destination: taxiupdate
          group: group
          binder: pubsub
          consumer:
            concurrency: 1
solace:
  java:
    host: ${host:tcp://localhost:55555}
    msgVpn: ${msgVpn:default}
    clientUsername: ${clientUsername:default}
    clientPassword: ${clientPassword:default}
  jms:
    host: ${host:tcp://localhost:55555}
    msg-vpn: ${msgVpn:default}
    client-username: ${clientUsername:default}
    client-password: ${clientPassword:default}
    direct-transport: true
    client-name: GoogleToSolaceBridge
logging:
  level:
    root: info
    org:
      springframework: info
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'

